// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/gps': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gps').default>>>>
    }
    '/_ws': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/_ws').default>>>>
    }
    '/favorites': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/favorites.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/favorites.post').default>>>>
    }
    '/give-roster-access': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/give-roster-access').default>>>>
    }
    '/gps-initiate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/gps-initiate.post').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/index.dev').default>>>>
    }
    '/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/login.post').default>>>>
    }
    '/logout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/logout').default>>>>
    }
    '/match': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/match.get').default>>>>
    }
    '/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/messages.get').default>>>>
    }
    '/messages/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/messages/[id].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/messages/[id].post').default>>>>
    }
    '/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/notifications.get').default>>>>
    }
    '/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/profile.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/profile.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/profile.put').default>>>>
    }
    '/ratings/:user_id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/ratings/[user_id].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/ratings/[user_id].post').default>>>>
    }
    '/ratings/:user_id/dispute/:rating_id': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/ratings/[user_id]/dispute/[rating_id].post').default>>>>
    }
    '/recipients': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/recipients.get').default>>>>
    }
    '/refresh': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/refresh.post').default>>>>
    }
    '/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/register.post').default>>>>
    }
    '/revoke-roster-access': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/revoke-roster-access').default>>>>
    }
    '/roster': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/roster.post').default>>>>
    }
    '/set-coord': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/set-coord.post.dev').default>>>>
    }
    '/subscription.dev': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/subscription.dev.post').default>>>>
    }
    '/subscription': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/subscription.get').default>>>>
    }
    '/visit-sessions/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/visit-sessions/[id]/index.get').default>>>>
    }
    '/visit-sessions/:id/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/visit-sessions/[id]/verify.post').default>>>>
    }
    '/visit-sessions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/visit-sessions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/visit-sessions/index.post').default>>>>
    }
  }
}
export {}